name: Build GnuChan Engine

on: [push, pull_request, workflow_dispatch]

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install SCons
        run: pip install scons

      - name: Build Editor
        run: scons -C src platform=windows tools=yes target=release_debug -j2
        env:
          SCONS_CACHE: ${{ github.workspace }}/.scons_cache

      - name: Upload Editor Binary
        uses: actions/upload-artifact@v4
        with:
          name: gnuchan-editor-windows
          path: src/bin/gnuchan.windows.opt.tools.64.exe

  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y build-essential scons pkg-config libx11-dev libxcursor-dev libxinerama-dev libgl1-mesa-dev libglu1-mesa-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev

      - name: Build Editor
        run: scons -C src platform=x11 tools=yes target=release_debug -j2
        env:
          SCONS_CACHE: ${{ github.workspace }}/.scons_cache

      - name: Upload Editor Binary
        uses: actions/upload-artifact@v4
        with:
          name: gnuchan-editor-linux
          path: src/bin/gnuchan.x11.opt.tools.64
